# Generated by Django 5.0.3 on 2024-03-10 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                (
                    "prop_type",
                    models.CharField(
                        choices=[
                            ("Кофейня", "Coffee"),
                            ("Ресторан", "Restaurant"),
                            ("Магазин", "Shop"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_franchise", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=256)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Формат телефона '+999999999'.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
